# Generated by Django 3.1.2 on 2020-10-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='артикул'),
        ),
    ]
